name: Node.js CI to Prod

on:
  push:
    branches: [ master ]

jobs:
  build-for-prod:

    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: githubtestapp
        publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
